import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import {ThemeProvider} from "@/components/providers/theme-provider";
import React from "react";
import {SidebarProvider} from "@/components/ui/sidebar";
import {AdminSidebar} from "@/components/layout/AdminSidebar";
import {cookies} from "next/headers";
import {AdminNavbar} from "@/components/layout/AdminNavbar";
import {QueryProvider} from "@/components/providers/query-provider";
import {ConfirmDialogProvider} from "@/components/providers/confirm-dialog-provider";
import {Toaster} from "sonner";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    const cookieStore = await cookies();
    const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
        >
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >
                <QueryProvider>
                    <ConfirmDialogProvider>
                        <SidebarProvider defaultOpen={defaultOpen}>
                            <AdminSidebar />
                            <main className={"w-full"}>
                                <AdminNavbar />
                                <div className={"px-4"}>
                                    {children}
                                    <Toaster
                                        position={"bottom-right"}
                                        richColors
                                    />
                                </div>
                            </main>
                        </SidebarProvider>
                    </ConfirmDialogProvider>
                </QueryProvider>
            </ThemeProvider>
        </body>
        </html>
    );
}
